GET http://localhost:8080/

###

POST http://localhost:8080/tokenGenerate

###

POST http://localhost:8080/verifyToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIzNDUsInVzZXJuYW1lIjoiQXVnRnJlc2hlcnMyMiIsImVtYWlsIjoiYXVnZnJlc2gyMkBjb2RpbmcuY29tIiwiaWF0IjoxNjc4NzIxNzcxfQ.dhE1ZsLTGB8b-Rmkv2gnHYvxy3o-MhZwCEiKrwNvPkk